name: Déploiement Automatique

on:
  push:
    branches:
      - main  # Déclenche le workflow lors d'un push sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v2

      - name: Déployer sur le serveur
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USER }}
          KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          ssh -i "${KEY}" -o StrictHostKeyChecking=no ${USERNAME}@${HOST} << 'EOF'
            cd /chemin/vers/votre/application
            git pull origin main
            npm install
            npm run build
            pm2 restart all
          EOF
