name: Déploiement Automatique

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v2

      - name: Configurer SSH
        env:
          KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          echo "${KEY}" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
          cat /tmp/deploy_key  # Ajoutez cette ligne pour vérifier le contenu de la clé privée

      - name: Déployer sur le serveur
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USER }}
        run: |
          ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no ${USERNAME}@${HOST} << 'EOF'
            cd /var/www/porte-folio-cyril
            git pull origin master
            npm install
            npm run build
            pm2 restart all
          EOF