name: Déployer sur AWS CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configurer AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ AKIAVDDALAA7EIRLE3XE }}
          aws-secret-access-key: ${{ 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 }}
          aws-region: us-east-1  # Remplacez par votre région AWS

      - name: Installer les dépendances
        run: |
          # Commandes pour installer les dépendances de votre projet
          npm install

      - name: Construire le projet
        run: |
          # Commandes pour construire votre projet
          npm run build

      - name: Déployer avec AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name Portfolio-cyril \
            --deployment-group-name CodeDeployPortfolio \
            --s3-location bucket=cyril-dohin.fr,key=cyril-dohin.fr.zip,bundleType=zip
