name: Deploy to AWS S3 and CloudFront

on:
  push:
    branches:
      - main # Remplacez par votre branche principale si différent

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Étape 2 : Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Utilisez la version Node.js compatible avec votre projet

      # Étape 3 : Installer les dépendances
      - name: Install Dependencies
        run: npm install

      # Étape 4 : Build du projet
      - name: Build Project
        run: npm run build

      # Étape 5 : Déployer sur S3
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: cyril-dohin.fr
          aws-access-key-id: AKIAVDDALAA7EIRLE3XE
          aws-secret-access-key: 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
          AWS_REGION: 'us-east-1' # Remplacez par votre région AWS
          SOURCE_DIR: 'dist'

      # Étape 6 : Invalider le cache CloudFront
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v1
        with:
          distribution: E30TZHHHE5ETBR # Remplacez par votre ID de distribution
          paths: "/*"
        env:
          aws-access-key-id: AKIAVDDALAA7EIRLE3XE
          aws-secret-access-key: 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

