name: Déployer sur GitHub Pages

on:
  push:
    branches:
      - main  # Branche déclenchant le déploiement

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configurer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Spécifiez la version de Node.js

      - name: Installer les dépendances
        run: npm install

      - name: Construire le projet
        run: npm run build

      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
