name: Déploiement Automatique

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Cloner le dépôt
        uses: actions/checkout@v2

      # Étape 2 : Installer les dépendances et construire le projet
      - name: Installer les dépendances et construire
        run: |
          npm install
          npx update-browserslist-db@latest --update-db
          npm run build

      # Étape 3 : Configurer SSH
      - name: Configurer SSH
        env:
          KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          echo "${KEY}" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key

          
      - name: Déployer sur le serveur
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USER }}
        run: |
          ssh -o ServerAliveInterval=60 -i /tmp/deploy_key -o StrictHostKeyChecking=no ${USERNAME}@${HOST} << 'EOF'
            cd /var/www/porte-folio-cyril
            git pull origin main
            npm install
            npm run build
            pm2 restart all
          EOF
